version: '3.7'

services:

  mongo:
    image: mongo:focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo

  backend:
    container_name: backend
    image: backend
    build: 
      context: .
      dockerfile: backend.dockerfile 
    environment:
      - PORT=3001
    expose:
      - 3001
    ports:
      - "3001:3001"
    restart: on-failure

  
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    