version: '3.7'

services:
  backend:
    container_name: backend
    image: backend
    build: 
      context: .
      dockerfile: backend.dockerfile 
    environment:
      - PORT=3001
    expose:
      - 3001
    ports:
      - "3001:3001"
    restart: on-failure

  
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    